version: '3'

services:
  db1os:
      image: mysql:5.7
      volumes:
            -mysql_db:/var/lib/mysql
      restart: always
      environment:
            MYSQL_ROOT_PASSWORD: docker
            MYSQL_USER: akanksha
            MYSQL_PASSWORD: docker
            MYSQL_DATABASE: db1

wordpressos:
      image: wordpress:5.1.1-php7.3-apache    
      restart: always
      depends_on:
           - db1os
      ports:
           - 8081:80               
                 volumes: 
                           - wordpress:/var/www/html
                 restart: always
                 environment:
                          WORDPRESS_DB_HOST: db1os
                          WORDPRESS_DB_USER: akanksha
                          WORDPRESS_DB_PASSWORD: docker
                          WORDPRESS_DB_NAME: db1
volumes:
        mysql_db:
        wordpress: 

              